apiVersion: v2
name: kube-dump
description: A Helm chart for kube-dump
type: application
version: "0.1.6" # set by GHA at Wed Oct 30 19:49:13 UTC 2024
appVersion: "0.1.6" # set by GHA at Wed Oct 30 19:49:13 UTC 2024
